version: 2
updates:
# Maintain dependencies for Docker
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "monthly"
# Maintain dependencies for Golang Modules
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "monthly"
