steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/go-gcp-pushover/notificationchannel',
      '.'
    ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'australia-southeast1-docker.pkg.dev/$PROJECT_ID/go-gcp-pushover/notificationchannel'
    ]

images:
  - australia-southeast1-docker.pkg.dev/$PROJECT_ID/go-gcp-pushover/notificationchannel

options:
  logging: CLOUD_LOGGING_ONLY 