steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/go-gcp-pushover/notificationchannel',
      '--build-arg', 'PUSHOVER_TOKEN=${_PUSHOVER_TOKEN}',
      '--build-arg', 'PUSHOVER_USERKEY=${_PUSHOVER_USERKEY}',
      '.'
    ]
    secretEnv: ['_PUSHOVER_TOKEN', '_PUSHOVER_USERKEY']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'australia-southeast1-docker.pkg.dev/$PROJECT_ID/go-gcp-pushover/notificationchannel'
    ]

images:
  - australia-southeast1-docker.pkg.dev/$PROJECT_ID/go-gcp-pushover/notificationchannel

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/555879821680/secrets/PUSHOVER_A/versions/latest
      env: '_PUSHOVER_TOKEN'
    - versionName: projects/555879821680/secrets/PUSHOVER_USER_ID/versions/latest
      env: '_PUSHOVER_USERKEY' 